Import('env')

env = env.Clone()
env.Append(
   LIBS=['-lm'] #, '-lstdc++']
)

libsources = Split("""
   agent.cc
   markov.cc
   rand.cc
   runner.cc
""")

lib = env.SharedLibrary('decider', libsources)
test = env.Program('test', ['main.cc'] + libsources)

env.Default(lib)
env.Alias('test', test)

# vim:set ft=python sw=3:
